name: Lint

on:
  push:
    branches: [master]
    paths:
      - common/define-grammar.js
      - grammar.js
      - eslint.config.mjs
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - common/define-grammar.js
      - grammar.js
      - eslint.config.mjs
      - package.json
      - package-lock.json
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
      - name: Install modules
        run: npm ci --legacy-peer-deps
      - name: Run ESLint
        run: npm run lint
